### ISSUE TITLE
It works !

### ISSUE THREAD

**Issue by adfaure** [swatteau/tmx#1]
Hi! 

Thanks for the project it works just fine.
Do you intend to maintain it, or was it just a one shot?

Best regards;
Adrien

**Comment by swatteau** [comment]
Hi Adrien,

Thanks for your interest in this project. I did it mainly because I wanted to practice TDD and because nobody had written a TMX reader in Rust yet.

At the moment, I have no further plan for it because I consider it pretty much done. I might however work on fixing issues as time allows.

**Comment by adfaure** [comment]
Hello;
thanks for the answer.

For the moment, it works well, but I think that I will maybe need to do some modification. For example; add a function to get layer from its name. This kind of stuff. 

Do you prefer that I work on a fork or do you want to get the updates ?

**Comment by swatteau** [comment]
Feel free to work on a fork. It is probably best because I think I won't have much time to review and merge pull requests on this project anyway.

**Comment by adfaure** [comment]
Okay, I'll close this issue then.

Thanks for your answers.

**Comment by phrohdoh** [comment]
@adfaure Just FYI https://github.com/mattyhall/rs-tiled exists so check that out too.

**Comment by adfaure** [comment]
@Phrohdoh  Hi, thank you, I saw this project too but I could not make it works :) 
(That is also why title of this issue is "It works !")

But the project seems interesting, and I'll keep checking it. In the meantime I'll use this project that works great ;)
